version: '3.4'

services:
  postgres-fastify:
    container_name: postgres-fastify
    image: postgres:13-alpine
    volumes:
      - ./.vscode/postgres-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "teste"
    ports: 
      - "5432:5432"
      
  # pgadmin-fastify:
  #   container_name: pgadmin-fastify
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "ian@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "123456"
  #   ports:
  #     - "4000:80"
  #   depends_on:
  #     - postgres-fastify
